<?php
$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
?>


<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<a class="navbar-brand" href="<?php echo $this->Url( array( 'module' => 'admin' ), null, true ) ?>">
				GuitarPrime
			</a>
		</div>
		<div class="navbar-collapse collapse">
			<ul class="nav navbar-nav">
				<?php if ( Zend_Auth::getInstance()->hasIdentity() ) { ?>
					<li <?php echo ( $module == 'admin' && $controller == 'user' ) ? 'class="active"' : '' ?>>
						<a href="<?php echo $this->url( array( 'module' => 'admin', 'controller' => 'user' ), null, true ); ?>">
							user
						</a>
					</li>
					<li <?php echo ( $module == 'admin' && $controller == 'language' ) ? 'class="active"' : '' ?>>
						<a href="<?php echo $this->url( array( 'module' => 'admin', 'controller' => 'language' ), null, true ); ?>">
							language
						</a>
					</li>
					<li <?php echo ( $module == 'admin' && $controller == 'instrument' ) ? 'class="active"' : '' ?>>
						<a href="<?php echo $this->url( array( 'module' => 'admin', 'controller' => 'instrument' ), null, true ); ?>">
							instrument
						</a>
					</li>
					<li <?php echo ( $module == 'admin' && $controller == 'category' ) ? 'class="active"' : '' ?>>
						<a href="<?php echo $this->url( array( 'module' => 'admin', 'controller' => 'category' ), null, true ); ?>">
							category
						</a>
					</li>
					<li <?php echo ( $module == 'admin' && $controller == 'sub-category' ) ? 'class="active"' : '' ?>>
						<a href="<?php echo $this->url( array( 'module' => 'admin', 'controller' => 'sub-category' ), null, true ); ?>">
							sub-category
						</a>
					</li>
					<li>
						<a href="<?php echo $this->url( array( 'module' => 'admin', 'controller' => 'user', 'action' => 'logout' ), null, true ); ?>">
							logout
						</a>
					</li>
				<?php } ?>
			</ul>
		</div>
	</div>
</div>