<?php $this->title = 'Sub-Package' ?>
<?php $this->subtitle = 'translate' ?>

<p class="pull-right">
	<?php echo $this->Link( $this->Icon( 'plus' ) . ' Adicionar', null, 'translate-add', array( 'id' => $this->id ) ) ?>
	&nbsp;&nbsp;
	<?php echo $this->Voltar( array( 'module' => 'admin', 'controller' => 'sub-package' ) ); ?>
</p>

<table class="table">
	<tr>
		<th>Language</th>
		<th>Name</th>
		<th>Description</th>
		<th>Options</th>
	</tr>
	<?php foreach ( $this->data as $row ): ?>
		<tr>
			<td><?php echo $row['languageName'] ?></td>
			<td><?php echo $row['subpackageTransName'] ?></td>
			<td><?php echo $row['subpackageTransDesc'] ?></td>
			<td>
				<?php echo $this->Link( $this->Icon( 'pencil' ), null, 'translate-edit', array( 'id' => $this->id, 'language' => $row['languageId'] ) ) ?>
				<?php echo $this->Link( $this->Icon( 'trash' ), null, 'translate-delete', array( 'id' => $this->id, 'language' => $row['languageId'] ) ) ?>
			</td>
		</tr>
	<?php endforeach; ?>
</table>