<?php $this->title = $this->translate( 'forgot-password' ); ?>

<?php echo $this->form; ?>

<p class="text-center form" style="padding: 0">
	<?php echo $this->translate( 'have-account-msg' ) ?>
	<strong>
		<a href="<?php echo $this->url( array( 'controller' => 'user', 'action' => 'sign-up' ), null, false ); ?>">
			<?php echo $this->translate( 'sign-up' ) ?>
		</a>
	</strong>
</p>
<p class="text-center form">
	<?php echo $this->translate( 'remember-password' ) ?>
	<strong>
		<a href="<?php echo $this->url( array( 'controller' => 'user', 'action' => 'login' ), null, false ); ?>">
			<?php echo $this->translate( 'login' ) ?>
		</a>
	</strong>
</p>