<div id="myCarousel" class="carousel slide" data-ride="carousel">
	<!-- Indicators -->
	<ol class="carousel-indicators">
		<?php $active = true; ?>
		<?php for ( $i = 0; $i < sizeof( $this->carousel ); $i++ ): ?>
			<li data-target="#myCarousel" data-slide-to="<?php echo $i ?>"
			    class="<?php echo $active ? 'active' : '' ?>"></li>
			<?php $active = false; ?>
		<?php endfor; ?>
	</ol>
	<div class="carousel-inner">
		<?php $active = true; ?>
		<?php foreach ( $this->carousel as $carousel ): ?>
			<div class="item<?php echo $active ? ' active' : '' ?>">
				<img alt="<?php echo $carousel['carouselTransTitle'] ?>"
				     src="<?php echo $this->baseUrl( '/files/' . $carousel['fileType'] . '/' . $carousel['fileSrc'] ) ?>">

				<div class="container">
					<div class="carousel-caption">
						<h1><?php echo $carousel['carouselTransTitle'] ?></h1>

						<p><?php echo $carousel['carouselTransDesc'] ?></p>

						<p><a class="btn btn-lg btn-primary" href="<?php echo $carousel['carouselUrl'] ?>"
						      role="button"><?php echo $carousel['carouselTransBtn'] ?></a></p>
					</div>
				</div>
			</div>
			<?php $active = false; ?>
		<?php endforeach; ?>
	</div>
	<a class="left carousel-control" href="#myCarousel" data-slide="prev"><span
			class="glyphicon glyphicon-chevron-left"></span></a>
	<a class="right carousel-control" href="#myCarousel" data-slide="next"><span
			class="glyphicon glyphicon-chevron-right"></span></a>
</div>