<?php $this->title = $this->translate( 'about' ); ?>
<?php $this->subtitle = 'guitarprime'; ?>


<ul id="myTab" class="nav nav-tabs">
	<li class="active">
		<a href="#about" data-toggle="tab"><?php echo $this->translate( 'about' ) ?></a>
	</li>
	<li class="">
		<a href="#members" data-toggle="tab"><?php echo $this->translate( 'members' ) ?></a>
	</li>
</ul>
<div id="myTabContent" class="tab-content">
	<div class="tab-pane fade active in" id="about">
		<p>Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro
			synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher
			retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid.
			Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate
			nisi qui.</p>
	</div>
	<div class="tab-pane fade" id="members">
		<?php echo $this->render( 'index/members.phtml' ) ?>
	</div>
</div>