<?php $this->carousel = $this->partial( 'layout/layout3/carousel.phtml', array( 'carousel' => $this->carousel ) ); ?>

<div class="row">
	<div class="col-lg-6">
		<div class="thumbnail">
			<img src="<?php echo $this->baseUrl() . '/img/carousel/guitar2.jpg' ?>">

			<div class="caption">
				<h3>Destaque</h3>

				<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor
					mauris
					condimentum nibh, ut fermentum massa ju...</p>

				<p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default"
				                                                                   role="button">Button</a></p>
			</div>
		</div>
	</div>
	<div class="col-lg-6">
		<div class="thumbnail">
			<img src="<?php echo $this->baseUrl() . '/img/carousel/guitar1.jpg' ?>">

			<div class="caption">
				<h3>Destaque</h3>

				<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor
					mauris
					condimentum nibh, ut fermentum massa ju...</p>

				<p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default"
				                                                                   role="button">Button</a></p>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-lg-4">
		<h2>Heading</h2>

		<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris
			condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod.
			Donec sed odio dui. </p>

		<p><a class="btn btn-default" href="#">View details »</a></p>
	</div>
	<div class="col-lg-4">
		<h2>Heading</h2>

		<p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta
			felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum
			massa justo sit amet risus.</p>

		<p><a class="btn btn-default" href="#">View details »</a></p>
	</div>
	<div class="col-lg-4">
		<h2>Heading</h2>

		<p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta
			felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum
			massa justo sit amet risus.</p>

		<p><a class="btn btn-default" href="#">View details »</a></p>
	</div>
</div>

<style type="text/css">
	.wrapper > .container {
		padding-top: 0px;
	}
</style>