<?php $this->title = $this->translate( 'results' ); ?>
<?php $this->subtitle = $this->search; ?>

<?php if ( $this->package ): ?>
    <h2><?php echo $this->translate( 'package' ) ?></h2>
    <?php foreach ( $this->package as $package ): ?>
        <h3>
            <a href="<?php echo $this->url( array( 'controller' => 'package', 'action' => 'view', 'id' => $package['packageId'] ), null, true ); ?>">
                <?php echo $package['packageTransName'] ?>
            </a>
        </h3>
    <?php endforeach; ?>
<?php endif; ?>

<?php if ( $this->blog ): ?>
    <h2>Blog</h2>
    <?php foreach ( $this->blog as $blog ): ?>
        <h3><?php echo $blog['blogTitle'] ?></h3>
    <?php endforeach; ?>
<?php endif; ?>