<footer>
	<div class="container">
		<div class="row">
			<div class="col-md-3">
				<div class="title">PAGES</div>
				<ul>
					<li>
						<a href="<?php echo $this->url( array( 'controller' => 'index' ), null, true ); ?>">
							HOME
						</a>
					</li>
					<li>
						<a href="<?php echo $this->url( array( 'controller' => 'index' ), null, true ); ?>">
							<?php echo mb_strtoupper( $this->translate( 'blog' ), 'ISO-8859-1' ) ?>
						</a>
					</li>
					<li>
						<a href="<?php echo $this->url( array( 'controller' => 'index', 'action' => 'contact' ), null, true ); ?>">
							<?php echo mb_strtoupper( $this->translate( 'contact' ), 'ISO-8859-1' ) ?>
						</a>
					</li>
					<li>
						<a href="<?php echo $this->url( array( 'controller' => 'index', 'action' => 'about' ), null, true ); ?>">
							<?php echo mb_strtoupper( $this->translate( 'about' ), 'ISO-8859-1' ) ?>
						</a>
					</li>
				</ul>
			</div>
			<div class="col-md-3">
				<div class="title"><?php echo mb_strtoupper( $this->translate( 'user' ), 'ISO-8859-1' ) ?></div>
				<ul>

					<?php if ( !Zend_Auth::getInstance()->hasIdentity() ) { ?>
						<li>
							<a href="<?php echo $this->url( array( 'controller' => 'user', 'action' => 'login' ), null, true ); ?>">
								<?php echo mb_strtoupper( $this->translate( 'login' ), 'ISO-8859-1' ) ?>
							</a>
						</li>
						<li>
							<a href="<?php echo $this->url( array( 'controller' => 'user', 'action' => 'sign-up' ), null, true ); ?>">
								<?php echo mb_strtoupper( $this->translate( 'sign-up' ), 'ISO-8859-1' ) ?>
							</a>
						</li>
					<?php } else { ?>
						<li>
							<a href="<?php echo $this->url( array( 'controller' => 'user' ), null, true ); ?>">
								<?php echo mb_strtoupper( $this->translate( 'account' ), 'ISO-8859-1' ) ?>
							</a>
						</li>
					<?php } ?>
				</ul>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12" id="footerCopyright">GuitarPrime © 2013</div>
		</div>
	</div>
</footer>