<?php
$this->setEncoding( 'utf-8' );
$this->headMeta()->appendHttpEquiv( 'Content-Type', 'text/html;charset=ISO-8859-1' );
$this->headMeta()->appendName( 'viewport', 'width=device-width, initial-scale=1.0' );

//incluir css
$this->headLink()->appendStylesheet( $this->baseUrl() . '/bootstrap/dist/css/bootstrap.min.css' );
$this->headLink()->appendStylesheet( $this->baseUrl() . '/css/layout4.css' );
$this->headLink()->appendStylesheet( $this->baseUrl() . '/css/footer4.css' );
$this->cssHelper( $this->baseUrl() );

//incluir js
$this->headScript()->appendFile( $this->baseUrl() . '/js/jquery-1.10.2.min.js' );
$this->headScript()->appendFile( $this->baseUrl() . '/bootstrap/dist/js/bootstrap.min.js' );
$this->javascriptHelper( $this->baseUrl() );
?>

<!DOCTYPE html>
<html lang="en">
<head>
	<?php echo $this->headMeta() ?>
	<?php echo $this->headTitle() ?>
	<?php echo $this->headLink() ?>
	<?php echo $this->headStyle() ?>
</head>
<body>

<?php echo $this->partial( 'layout/layout4/header.phtml' ); ?>

<?php
if ( Zend_Controller_Front::getInstance()->getRequest()->getControllerName() == 'index' && Zend_Controller_Front::getInstance()->getRequest()->getActionName() == 'index' ) {
	echo $this->partial( 'layout/layout4/jumbotron.phtml' );
}
?>

<div class="wrapper">
	<div class="container">
		<?php if ( isset( $this->title ) ) : ?>
			<div class="page-header">
				<h1>
					<?php echo $this->title ?>
					<?php if ( isset( $this->subtitle ) ) : ?>
						<small><?php echo $this->subtitle ?></small>
					<?php endif; ?>
				</h1>
			</div>
		<?php endif; ?>
		<?php echo $this->alertMessages(); ?>
		<?php echo $this->layout()->content; ?>
	</div>
	<div class="push"><!--//--></div>
</div>

<?php echo $this->partial( 'layout/layout4/footer.phtml' ); ?>


<?php echo $this->headScript() ?>
</body>
</html>
