<?php $this->title = 'File' ?>

<p class="pull-right"><?php echo $this->AddLinkHelper(); ?></p>

<table class="table">
	<tr>
		<th>Id</th>
		<th>Name</th>
		<th>Type</th>
		<th>Src</th>
		<th>Date</th>
		<th>Options</th>
	</tr>
	<?php foreach ( $this->data as $row ): ?>
		<tr>
			<td><?php echo $row['fileId'] ?></td>
			<td><?php echo $row['fileName'] ?></td>
			<td><?php echo $row['fileType'] ?></td>
			<td><?php echo $row['fileSrc'] ?></td>
			<td><?php echo $row['fileDate'] ?></td>
			<td>
				<?php //echo $this->Edit( $row['fileId'] ) ?>
				<?php echo $this->ConfirmDelete( $row['fileId'] ) ?>
				<?php echo $this->Link( $this->Icon( 'download' ) )
					->setUrl( $this->baseUrl( '/files/' . $row['fileType'] . '/' . $row['fileSrc'] ) )
					->setAttribute( 'target', '_blank' )
				?>
			</td>
		</tr>
	<?php endforeach; ?>
</table>