<footer>
	<div class="container">
		<div class="row">
			<div class="col-md-3">
				<ul>
					<li>
						<a href="<?php echo $this->url( array( 'controller' => 'index' ), null, false ); ?>">
							HOME
						</a>
					</li>
					<li>
						<a href="<?php echo $this->url( array( 'controller' => 'index' ), null, false ); ?>">
							<?php echo strtoupper( $this->translate( 'blog' ) ) ?>
						</a>
					</li>
					<li>
						<a href="<?php echo $this->url( array( 'controller' => 'index', 'action' => 'contact' ), null, false ); ?>">
							<?php echo strtoupper( $this->translate( 'contact' ) ) ?>
						</a>
					</li>
					<li>
						<a href="<?php echo $this->url( array( 'controller' => 'index', 'action' => 'about' ), null, false ); ?>">
							<?php echo strtoupper( $this->translate( 'about' ) ) ?>
						</a>
					</li>
				</ul>
			</div>
			<div class="col-md-3">
				<ul>
					<li>
						<a href="<?php echo $this->url( array( 'controller' => 'index' ), null, false ); ?>">
							HOME
						</a>
					</li>
					<li>
						<a href="<?php echo $this->url( array( 'controller' => 'index' ), null, false ); ?>">
							<?php echo strtoupper( $this->translate( 'blog' ) ) ?>
						</a>
					</li>
					<li>
						<a href="<?php echo $this->url( array( 'controller' => 'index', 'action' => 'contact' ), null, false ); ?>">
							<?php echo strtoupper( $this->translate( 'contact' ) ) ?>
						</a>
					</li>
					<li>
						<a href="<?php echo $this->url( array( 'controller' => 'index', 'action' => 'about' ), null, false ); ?>">
							<?php echo strtoupper( $this->translate( 'about' ) ) ?>
						</a>
					</li>
				</ul>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12" id="footerCopyright">GuitarPrime © 2013</div>
		</div>
	</div>
</footer>