<div class="navbar navbar-inverse navbar-static-top">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="<?php echo $this->Url( array( 'controller' => 'index' ), null, true ) ?>">project</a>
		</div>
		<div class="navbar-collapse collapse">
			<ul class="nav navbar-nav">
				<li class="active">
					<a href="<?php echo $this->Url( array( 'controller' => 'index' ), null, true ) ?>">Home</a>
				</li>
				<li>
					<a href="#"><?php echo $this->translate( 'blog' ) ?></a>
				</li>
				<li>
					<a href="<?php echo $this->Url( array( 'controller' => 'index', 'action' => 'about' ), null, true ) ?>"><?php echo $this->translate( 'about' ) ?></a>
				</li>
				<li>
					<a href="<?php echo $this->Url( array( 'controller' => 'index', 'action' => 'contact' ), null, true ) ?>"><?php echo $this->translate( 'contact' ) ?></a>
				</li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li><a href="#">Action</a></li>
						<li><a href="#">Another action</a></li>
						<li><a href="#">Something else here</a></li>
						<li class="divider"></li>
						<li class="dropdown-header">Nav header</li>
						<li><a href="#">Separated link</a></li>
						<li><a href="#">One more separated link</a></li>
					</ul>
				</li>
			</ul>
			<?php if ( Zend_Auth::getInstance()->hasIdentity() ) { ?>
				<ul class="nav navbar-nav navbar-right">
					<li><?php echo Zend_Auth::getInstance()->getIdentity()->getUserName(); ?>,</li>
					<li>
						<a href="<?php echo $this->url( array( 'controller' => 'user' ), null, false ); ?>">
							<?php echo $this->translate( 'account' ) ?>
						</a>
					</li>
					<li>
						<a href="<?php echo $this->url( array( 'controller' => 'user', 'action' => 'logout' ), null, false ); ?>">
							<?php echo $this->translate( 'logout' ) ?>
						</a>
					</li>
				</ul>
			<?php } else { ?>
				<!--/.navbar-collapse -->
				<form class="navbar-form navbar-right" method="post"
				      action="<?php echo $this->Url( array( 'controller' => 'user', 'action' => 'login' ), null, true ) ?>">
					<a href="<?php echo $this->url( array( 'controller' => 'user', 'action' => 'sign-up' ), null, false ); ?>">
						<?php echo $this->translate( 'sign-up' ) ?>
					</a>
					<div class="form-group">
						<input type="text" placeholder="<?php echo $this->translate( 'mail' ) ?>" class="form-control input-sm"
						       name="userMail">
					</div>
					<div class="form-group">
						<input type="password" placeholder="<?php echo $this->translate( 'password' ) ?>"
						       class="form-control input-sm" name="userPassword">
					</div>
					<button type="submit" class="btn btn-success btn-sm"><?php echo $this->translate( 'login' ) ?></button>
				</form>
			<?php } ?>
		</div>
	</div>
</div>