<?php $this->title = 'Blog' ?>

<p class="pull-right"><?php echo $this->AddLinkHelper(); ?></p>

<table class="table">
	<tr>
		<th>Id</th>
		<th>Title</th>
		<th>Date</th>
		<th>Author</th>
		<th>Options</th>
	</tr>
	<?php foreach ( $this->data as $row ): ?>
		<tr>
			<td><?php echo $row['blogId'] ?></td>
			<td><?php echo $row['blogTitle'] ?></td>
			<td><?php echo $row['blogDate'] ?></td>
			<td><?php echo $row['adminFullName'] ?></td>
			<td>
				<?php echo $this->Edit( $row['blogId'] ) ?>
				<?php echo $this->ConfirmDelete( $row['blogId'] ) ?>
			</td>
		</tr>
	<?php endforeach; ?>
</table>