<?php $this->title = 'Package' ?>

<p class="pull-right"><?php echo $this->AddLinkHelper(); ?></p>

<table class="table">
	<tr>
		<th>Id</th>
		<th>Name</th>
		<th>Category</th>
		<th>Sub Category</th>
		<th>Instrument</th>
		<th>Author</th>
		<th>Options</th>
	</tr>
	<?php foreach ( $this->data as $row ): ?>
		<tr>
			<td><?php echo $row['packageId'] ?></td>
			<td><?php echo $row['packageName'] ?></td>
			<td><?php echo $row['categoryName'] ?></td>
			<td><?php echo $row['subCategoryName'] ?></td>
			<td><?php echo $row['instrumentName'] ?></td>
			<td><?php echo $row['authorName'] ?></td>
			<td>
				<?php echo $this->Edit( $row['packageId'] ) ?>
				<?php echo $this->ConfirmDelete( $row['packageId'] ) ?>
				<?php echo $this->Link( $this->Icon( 'random' ), null, 'translate', array( 'id' => $row['packageId'] ) ) ?>
				<?php echo $this->Link( $this->Icon( 'glyphicon-th-large' ), 'sub-package', 'index', array( 'package' => $row['packageId'] ) ) ?>
			</td>
		</tr>
	<?php endforeach; ?>
</table>