<?php $this->title = 'Category' ?>

<p class="pull-right"><?php echo $this->AddLinkHelper(); ?></p>

<table class="table">
	<tr>
		<th>Id</th>
		<th>Name</th>
		<th>Options</th>
	</tr>
	<?php foreach ( $this->data as $row ): ?>
		<tr>
			<td><?php echo $row['categoryId'] ?></td>
			<td><?php echo $row['categoryName'] ?></td>
			<td>
				<?php echo $this->Edit( $row['categoryId'] ) ?>
				<?php echo $this->ConfirmDelete( $row['categoryId'] ) ?>
			</td>
		</tr>
	<?php endforeach; ?>
</table>